"""add id column in ChatTranscriptCursor 

Revision ID: 028522193d41
Revises: 16170e8feda9
Create Date: 2026-09-16 19:53:05.484569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '028522193d41'
down_revision: Union[str, Sequence[str], None] = '16170e8feda9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chattranscriptcursor', sa.Column('id', sa.Uuid(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chattranscriptcursor', 'id')
    # ### end Alembic commands ###
