"""add MeetingChatRealtion and TranscriptLogs table deleted interview_id field from ChatSession

Revision ID: 0447baebaf81
Revises: 8857aaa64059
Create Date: 2026-09-11 14:22:32.813839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '0447baebaf81'
down_revision: Union[str, Sequence[str], None] = '8857aaa64059'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetingchatrelation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('meeting_id', sa.Uuid(), nullable=False),
    sa.Column('chat_session_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chatsession.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['interviewsession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcriptlogs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('meeting_id', sa.Uuid(), nullable=False),
    sa.Column('transcript_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['interviewsession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('chatsession_interview_session_id_fkey'), 'chatsession', type_='foreignkey')
    op.drop_column('chatsession', 'interview_session_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatsession', sa.Column('interview_session_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('chatsession_interview_session_id_fkey'), 'chatsession', 'interviewsession', ['interview_session_id'], ['id'])
    op.drop_table('transcriptlogs')
    op.drop_table('meetingchatrelation')
    # ### end Alembic commands ###
