"""add chat_id column in ChatTranscriptCursor and drop chat_session_id column

Revision ID: 16170e8feda9
Revises: 9d1136378aa5
Create Date: 2026-09-16 19:43:20.226106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '16170e8feda9'
down_revision: Union[str, Sequence[str], None] = '9d1136378aa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chattranscriptcursor', sa.Column('chat_id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('chattranscriptcursor_chat_session_id_fkey'), 'chattranscriptcursor', type_='foreignkey')
    op.create_foreign_key(None, 'chattranscriptcursor', 'chatmessages', ['chat_id'], ['id'])
    op.drop_column('chattranscriptcursor', 'chat_session_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chattranscriptcursor', sa.Column('chat_session_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chattranscriptcursor', type_='foreignkey')
    op.create_foreign_key(op.f('chattranscriptcursor_chat_session_id_fkey'), 'chattranscriptcursor', 'threads', ['chat_session_id'], ['id'])
    op.drop_column('chattranscriptcursor', 'chat_id')
    # ### end Alembic commands ###
