"""add thread_id column in  ChatMessages table

Revision ID: 28c987a26c82
Revises: ae5a139853de
Create Date: 2026-09-22 00:31:14.470558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '28c987a26c82'
down_revision: Union[str, Sequence[str], None] = 'ae5a139853de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatmessages', sa.Column('thread_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'chatmessages', 'threads', ['thread_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chatmessages', type_='foreignkey')
    op.drop_column('chatmessages', 'thread_id')
    # ### end Alembic commands ###
