"""drop thread_id column from ChatMessages

Revision ID: 2b2038ae0683
Revises: 028522193d41
Create Date: 2026-09-16 20:02:41.149832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2b2038ae0683'
down_revision: Union[str, Sequence[str], None] = '028522193d41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chatmessages_thread_id_fkey'), 'chatmessages', type_='foreignkey')
    op.drop_column('chatmessages', 'thread_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatmessages', sa.Column('thread_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('chatmessages_thread_id_fkey'), 'chatmessages', 'threads', ['thread_id'], ['id'])
    # ### end Alembic commands ###
