"""migration: dropped interviewsession_id column from threads and add workspace_id

Revision ID: 35ed7db6577e
Revises: bf3e101933d7
Create Date: 2026-09-14 18:49:33.683225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '35ed7db6577e'
down_revision: Union[str, Sequence[str], None] = 'bf3e101933d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threads', sa.Column('workspace_id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('threads_interview_session_id_fkey'), 'threads', type_='foreignkey')
    op.create_foreign_key(None, 'threads', 'workspace', ['workspace_id'], ['id'])
    op.drop_column('threads', 'interview_session_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threads', sa.Column('interview_session_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'threads', type_='foreignkey')
    op.create_foreign_key(op.f('threads_interview_session_id_fkey'), 'threads', 'interviewsession', ['interview_session_id'], ['id'])
    op.drop_column('threads', 'workspace_id')
    # ### end Alembic commands ###
