"""drop organization_id, attendee_id, candidate_name, candidate_column and scheduled_date column from Meeting

Revision ID: 3dc0613ec9a2
Revises: d3db6e2d6322
Create Date: 2026-09-16 17:36:09.740221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3dc0613ec9a2'
down_revision: Union[str, Sequence[str], None] = 'd3db6e2d6322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('meeting_attendee_id_fkey'), 'meeting', type_='foreignkey')
    op.drop_constraint(op.f('meeting_organization_id_fkey'), 'meeting', type_='foreignkey')
    op.drop_column('meeting', 'attendee_id')
    op.drop_column('meeting', 'scheduled_date')
    op.drop_column('meeting', 'candidate_email')
    op.drop_column('meeting', 'organization_id')
    op.drop_column('meeting', 'candidate_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting', sa.Column('candidate_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('meeting', sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('meeting', sa.Column('candidate_email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('meeting', sa.Column('scheduled_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('meeting', sa.Column('attendee_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('meeting_organization_id_fkey'), 'meeting', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(op.f('meeting_attendee_id_fkey'), 'meeting', 'user', ['attendee_id'], ['id'])
    # ### end Alembic commands ###
