"""migrate: add created_by and organization_id columns in Workspace table

Revision ID: 85bd13811e48
Revises: ff7a3a6a54d9
Create Date: 2026-09-14 19:56:29.378876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '85bd13811e48'
down_revision: Union[str, Sequence[str], None] = 'ff7a3a6a54d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace', sa.Column('organization_id', sa.Uuid(), nullable=False))
    op.add_column('workspace', sa.Column('created_by', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'workspace', 'user', ['created_by'], ['id'])
    op.create_foreign_key(None, 'workspace', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspace', type_='foreignkey')
    op.drop_constraint(None, 'workspace', type_='foreignkey')
    op.drop_column('workspace', 'created_by')
    op.drop_column('workspace', 'organization_id')
    # ### end Alembic commands ###
