"""add MessageContext and AppSettings table

Revision ID: 8857aaa64059
Revises: e3a4703d1a85
Create Date: 2026-09-09 13:49:56.138902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8857aaa64059'
down_revision: Union[str, Sequence[str], None] = 'e3a4703d1a85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appsettings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('opacity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messagecontext',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chat_session_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chatsession.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('chatsession', 'timestamp',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               postgresql_using='timestamp::timestamp without time zone',
               existing_nullable=False)
    op.add_column('interviewsession', sa.Column('scheduled_date', sa.DateTime(), nullable=True))
    op.drop_column('interviewsession', 'scheduled_time')
    op.alter_column('invitation', 'is_accepted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('invitation', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               postgresql_using='created_at::timestamp without time zone',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invitation', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               postgresql_using='created_at::varchar',
               existing_nullable=False)
    op.alter_column('invitation', 'is_accepted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('interviewsession', sa.Column('scheduled_time', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('interviewsession', 'scheduled_date')
    op.alter_column('chatsession', 'timestamp',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               postgresql_using='timestamp::varchar',
               existing_nullable=False)
    op.drop_table('messagecontext')
    op.drop_table('appsettings')
    # ### end Alembic commands ###
