"""drop organization_id column from ChatMessages

Revision ID: 93464aa7a68d
Revises: f818d28aab9b
Create Date: 2026-09-15 18:13:40.974236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '93464aa7a68d'
down_revision: Union[str, Sequence[str], None] = 'f818d28aab9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chatmessages_org_id_fkey'), 'chatmessages', type_='foreignkey')
    op.drop_column('chatmessages', 'org_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatmessages', sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('chatmessages_org_id_fkey'), 'chatmessages', 'organizations', ['org_id'], ['id'])
    # ### end Alembic commands ###
