"""add chat messages, transcript sequencing, and cursor tracking rename message context to chat messages and add interview and invitation statuses

Revision ID: 939ce4cd54a5
Revises: 0447baebaf81
Create Date: 2026-09-11 17:41:20.145612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '939ce4cd54a5'
down_revision: Union[str, Sequence[str], None] = '0447baebaf81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatmessages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chat_session_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chatsession.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chattranscriptcursor',
    sa.Column('chat_session_id', sa.Uuid(), nullable=False),
    sa.Column('last_seen_seq', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chatsession.id'], ),
    sa.PrimaryKeyConstraint('chat_session_id')
    )
    op.drop_table('meetingchatrelation')
    op.drop_table('messagecontext')
    op.add_column('chatsession', sa.Column('interview_session_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'chatsession', 'interviewsession', ['interview_session_id'], ['id'])
    op.add_column('invitation', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('invitation', 'is_accepted')
    op.add_column('transcriptlogs', sa.Column('seq', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcriptlogs', 'seq')
    op.add_column('invitation', sa.Column('is_accepted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('invitation', 'status')
    op.drop_constraint(None, 'chatsession', type_='foreignkey')
    op.drop_column('chatsession', 'interview_session_id')
    op.create_table('messagecontext',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chat_session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chatsession.id'], name=op.f('messagecontext_chat_session_id_fkey')),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('messagecontext_org_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('messagecontext_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('messagecontext_pkey'))
    )
    op.create_table('meetingchatrelation',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('meeting_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chat_session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chatsession.id'], name=op.f('meetingchatrelation_chat_session_id_fkey')),
    sa.ForeignKeyConstraint(['meeting_id'], ['interviewsession.id'], name=op.f('meetingchatrelation_meeting_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('meetingchatrelation_pkey'))
    )
    op.drop_table('chattranscriptcursor')
    op.drop_table('chatmessages')
    # ### end Alembic commands ###
