"""add organizationn_id column in  Meeting table

Revision ID: ae5a139853de
Revises: 2b2038ae0683
Create Date: 2026-09-22 00:25:15.347623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ae5a139853de'
down_revision: Union[str, Sequence[str], None] = '2b2038ae0683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting', sa.Column('organization_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'meeting', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meeting', type_='foreignkey')
    op.drop_column('meeting', 'organization_id')
    # ### end Alembic commands ###
