"""add workspace, memory, workspacedocument and document model and renamed chatsessions to threads and fixed other tables where it refreenced it

Revision ID: b281a2575e5f
Revises: 939ce4cd54a5
Create Date: 2026-09-14 18:35:25.881625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b281a2575e5f'
down_revision: Union[str, Sequence[str], None] = '939ce4cd54a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workspace',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('system_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('history_limit', sa.Integer(), nullable=False),
    sa.Column('top_n', sa.Integer(), nullable=False),
    sa.Column('similarity_threshold', sa.Float(), nullable=False),
    sa.Column('chat_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vector_search_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('query_refusal_response', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('workspacedocument',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('workspace_id', 'document_id')
    )
    op.create_table('threads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('interview_session_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['interview_session_id'], ['interviewsession.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memory',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('chat_session_id', sa.Uuid(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('memory_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_session_id'], ['threads.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('chatmessages_chat_session_id_fkey'), 'chatmessages', type_='foreignkey')
    op.create_foreign_key(None, 'chatmessages', 'threads', ['chat_session_id'], ['id'])
    op.drop_constraint(op.f('chattranscriptcursor_chat_session_id_fkey'), 'chattranscriptcursor', type_='foreignkey')
    op.create_foreign_key(None, 'chattranscriptcursor', 'threads', ['chat_session_id'], ['id'])
    op.drop_table('chatsession')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatsession',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('interview_session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['interview_session_id'], ['interviewsession.id'], name=op.f('chatsession_interview_session_id_fkey')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('chatsession_organization_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('chatsession_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('chatsession_pkey'))
    )
    op.drop_constraint(None, 'chattranscriptcursor', type_='foreignkey')
    op.create_foreign_key(op.f('chattranscriptcursor_chat_session_id_fkey'), 'chattranscriptcursor', 'chatsession', ['chat_session_id'], ['id'])
    op.drop_constraint(None, 'chatmessages', type_='foreignkey')
    op.create_foreign_key(op.f('chatmessages_chat_session_id_fkey'), 'chatmessages', 'chatsession', ['chat_session_id'], ['id'])
    op.drop_table('memory')
    op.drop_table('threads')
    op.drop_table('workspacedocument')
    op.drop_table('workspace')
    op.drop_table('document')
    # ### end Alembic commands ###
