"""drop chat_session_id column from ChatMessages

Revision ID: d3db6e2d6322
Revises: 93464aa7a68d
Create Date: 2026-09-15 18:43:30.130580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd3db6e2d6322'
down_revision: Union[str, Sequence[str], None] = '93464aa7a68d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chatmessages_chat_session_id_fkey'), 'chatmessages', type_='foreignkey')
    op.drop_column('chatmessages', 'chat_session_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatmessages', sa.Column('chat_session_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('chatmessages_chat_session_id_fkey'), 'chatmessages', 'threads', ['chat_session_id'], ['id'])
    # ### end Alembic commands ###
