"""Add organization memberships.

Revision ID: dfce6f7a026b
Revises: 
Create Date: 2026-09-08 18:05:08.376651

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'dfce6f7a026b'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizationmember',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('organization_id', 'user_id')
    )
    op.execute(
        sa.text(
            """
            INSERT INTO organizationmember (organization_id, user_id, role)
            SELECT org_id, id, role
            FROM "user"
            WHERE org_id IS NOT NULL
            """
        )
    )
    op.drop_constraint(op.f('user_org_id_fkey'), 'user', type_='foreignkey')
    op.drop_column('user', 'org_id')
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user',
        sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        'user',
        sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f('user_org_id_fkey'),
        'user',
        'organizations',
        ['org_id'],
        ['id'],
    )
    op.drop_table('organizationmember')
    # ### end Alembic commands ###
