"""add interview adn chat tables

Revision ID: e3a4703d1a85
Revises: dfce6f7a026b
Create Date: 2026-09-08 19:57:00.414143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e3a4703d1a85'
down_revision: Union[str, Sequence[str], None] = 'dfce6f7a026b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatsession',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('interview_session_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['interview_session_id'], ['interviewsession.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('interviewsession', sa.Column('attendee_id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('interviewsession_user_id_fkey'), 'interviewsession', type_='foreignkey')
    op.create_foreign_key(None, 'interviewsession', 'user', ['attendee_id'], ['id'])
    op.drop_column('interviewsession', 'user_id')
    op.add_column('invitation', sa.Column('is_accepted', sa.Boolean(), nullable=False))
    op.add_column('invitation', sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invitation', 'created_at')
    op.drop_column('invitation', 'is_accepted')
    op.add_column('interviewsession', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'interviewsession', type_='foreignkey')
    op.create_foreign_key(op.f('interviewsession_user_id_fkey'), 'interviewsession', 'user', ['user_id'], ['id'])
    op.drop_column('interviewsession', 'attendee_id')
    op.drop_table('chatsession')
    # ### end Alembic commands ###
