"""drop content column fron ChatMessages and add query adn response column

Revision ID: f818d28aab9b
Revises: a87cc3049816
Create Date: 2026-09-15 18:09:56.575001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f818d28aab9b'
down_revision: Union[str, Sequence[str], None] = 'a87cc3049816'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatmessages', sa.Column('query', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('chatmessages', sa.Column('response', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('chatmessages', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatmessages', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('chatmessages', 'response')
    op.drop_column('chatmessages', 'query')
    # ### end Alembic commands ###
