"""fix: use enums for invitation and interview status fields and dropped InterviewSession table

Revision ID: ff7a3a6a54d9
Revises: 35ed7db6577e
Create Date: 2026-09-14 18:54:03.354326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff7a3a6a54d9'
down_revision: Union[str, Sequence[str], None] = '35ed7db6577e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    invitation_status = sa.Enum(
        'PENDING', 'ACCEPTED', 'REJECTED', name='invitationstatus'
    )
    invitation_status.create(op.get_bind(), checkfirst=True)
    op.create_table('meeting',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('attendee_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('candidate_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'CANCELLED', name='interviewstatus'), nullable=False),
    sa.ForeignKeyConstraint(['attendee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('transcriptlogs_meeting_id_fkey'), 'transcriptlogs', type_='foreignkey')
    op.drop_table('interviewsession')
    op.alter_column('invitation', 'status',
               existing_type=sa.VARCHAR(),
               type_=invitation_status,
               postgresql_using="upper(status)::invitationstatus",
               existing_nullable=True)
    op.create_foreign_key(None, 'transcriptlogs', 'meeting', ['meeting_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transcriptlogs', type_='foreignkey')
    op.create_foreign_key(op.f('transcriptlogs_meeting_id_fkey'), 'transcriptlogs', 'interviewsession', ['meeting_id'], ['id'])
    op.alter_column('invitation', 'status',
               existing_type=sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='invitationstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.create_table('interviewsession',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('candidate_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('candidate_email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('attendee_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('scheduled_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['attendee_id'], ['user.id'], name=op.f('interviewsession_attendee_id_fkey')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('interviewsession_organization_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('interviewsession_pkey'))
    )
    op.drop_table('meeting')
    # ### end Alembic commands ###
